package com.core.entities;
// Generated 30-ene-2016 19:36:23 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Numeros generated by hbm2java
 */
@Entity
@Table(name="numeros"
    ,schema="public"
)
public class Numeros  implements java.io.Serializable {


     private String numero;
     private String operadora;

    public Numeros() {
    }

    public Numeros(String numero, String operadora) {
       this.numero = numero;
       this.operadora = operadora;
    }
   
     @Id 

    
    @Column(name="numero", unique=true, nullable=false, length=32)
    public String getNumero() {
        return this.numero;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }

    
    @Column(name="operadora", nullable=false, length=32)
    public String getOperadora() {
        return this.operadora;
    }
    
    public void setOperadora(String operadora) {
        this.operadora = operadora;
    }




}


