package com.core.entities;
// Generated 30-ene-2016 19:36:23 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Recarga generated by hbm2java
 */
@Entity
@Table(name="recarga"
    ,schema="public"
)
public class Recarga  implements java.io.Serializable {


     private long nroVenta;
     private long nroRecarga;
     private Date fechaVenta;
     private String destino;
     private String producto;
     private String estadoVenta;
     private String estadoRecurso;
     private String acceso;
     private double monto;
     private Date fechaRecarga;
     private String refOperadora;

    public Recarga() {
    }

	
    public Recarga(long nroVenta, long nroRecarga, Date fechaVenta, double monto, Date fechaRecarga) {
        this.nroVenta = nroVenta;
        this.nroRecarga = nroRecarga;
        this.fechaVenta = fechaVenta;
        this.monto = monto;
        this.fechaRecarga = fechaRecarga;
    }
    public Recarga(long nroVenta, long nroRecarga, Date fechaVenta, String destino, String producto, String estadoVenta, String estadoRecurso, String acceso, double monto, Date fechaRecarga, String refOperadora) {
       this.nroVenta = nroVenta;
       this.nroRecarga = nroRecarga;
       this.fechaVenta = fechaVenta;
       this.destino = destino;
       this.producto = producto;
       this.estadoVenta = estadoVenta;
       this.estadoRecurso = estadoRecurso;
       this.acceso = acceso;
       this.monto = monto;
       this.fechaRecarga = fechaRecarga;
       this.refOperadora = refOperadora;
    }
   
     @Id 

    
    @Column(name="nro_venta", unique=true, nullable=false)
    public long getNroVenta() {
        return this.nroVenta;
    }
    
    public void setNroVenta(long nroVenta) {
        this.nroVenta = nroVenta;
    }

    
    @Column(name="nro_recarga", nullable=false)
    public long getNroRecarga() {
        return this.nroRecarga;
    }
    
    public void setNroRecarga(long nroRecarga) {
        this.nroRecarga = nroRecarga;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_venta", nullable=false, length=35)
    public Date getFechaVenta() {
        return this.fechaVenta;
    }
    
    public void setFechaVenta(Date fechaVenta) {
        this.fechaVenta = fechaVenta;
    }

    
    @Column(name="destino", length=32)
    public String getDestino() {
        return this.destino;
    }
    
    public void setDestino(String destino) {
        this.destino = destino;
    }

    
    @Column(name="producto", length=32)
    public String getProducto() {
        return this.producto;
    }
    
    public void setProducto(String producto) {
        this.producto = producto;
    }

    
    @Column(name="estado_venta", length=32)
    public String getEstadoVenta() {
        return this.estadoVenta;
    }
    
    public void setEstadoVenta(String estadoVenta) {
        this.estadoVenta = estadoVenta;
    }

    
    @Column(name="estado_recurso", length=32)
    public String getEstadoRecurso() {
        return this.estadoRecurso;
    }
    
    public void setEstadoRecurso(String estadoRecurso) {
        this.estadoRecurso = estadoRecurso;
    }

    
    @Column(name="acceso", length=32)
    public String getAcceso() {
        return this.acceso;
    }
    
    public void setAcceso(String acceso) {
        this.acceso = acceso;
    }

    
    @Column(name="monto", nullable=false, precision=17, scale=17)
    public double getMonto() {
        return this.monto;
    }
    
    public void setMonto(double monto) {
        this.monto = monto;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_recarga", nullable=false, length=35)
    public Date getFechaRecarga() {
        return this.fechaRecarga;
    }
    
    public void setFechaRecarga(Date fechaRecarga) {
        this.fechaRecarga = fechaRecarga;
    }

    
    @Column(name="ref_operadora", length=128)
    public String getRefOperadora() {
        return this.refOperadora;
    }
    
    public void setRefOperadora(String refOperadora) {
        this.refOperadora = refOperadora;
    }




}


